HSMS/Models/ErrorViewModel.cs
using System;

namespace HSMS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HSMS/ViewModels/SetupViewModels/AmmenitiesViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace com.bkss.ViewModels
{
    public class AmmenityViewModel
    {
        [Required]
        public string SchoolName { get; set; }
    }
}

HSMS/ViewModels/SetupViewModels/FinanceViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace com.bkss.ViewModels
{
    public class FinanceViewModel
    {
        [Required]
        public string SchoolName { get; set; }
    }
}

HSMS/ViewModels/SetupViewModels/SchoolViewModels.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace com.bkss.ViewModels
{
    public class AddSchoolViewModel
    {
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "The School Field is required")]
        public int School { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "This Field is required")]
        public int Country { get; set; }
        public string County { get; set; }
        [Required]
        public string Code { get; set; }
        public string Motto { get; set; }
        public string WorkPhone { get; set; }
        public string MobilePhone { get; set; }
        [Required]
        public string Email { get; set; }
        public string Street { get; set; }
        [Required]
        public string ContactName { get; set; }
        public string City { get; set; }
        [Required]
        public string PostalCode { get; set; }
    }
    public class AddLevelViewModel
    {
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int Level { get; set; }
        [Required]
        public string Name { get; set; }
    }
    public class AddClassViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "This Field is required")]
        public int Department { get; set; }
        [Required]
        public int Stream { get; set; }
    }
    public class AddDepartmentViewModel
    {
        [Required]
        public string DepartmentName { get; set; }
        [Required]
        public int Type { get; set; }
    }
    public class AddStreamViewModel
    {
        [Required]
        public string StreamName { get; set; }
    }
    public class AddOfficeViewModel
    {
        [Required]
        public string Name { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "This Field is required")]
        public int Department { get; set; }
    }
}

HSMS/Controllers/ErrorController.cs
namespace com.bkss.Controllers
{
    using Boilerplate.AspNetCore;
    using Microsoft.AspNetCore.Mvc;
    using com.bkss.Constants;

    /// <summary>
    /// Provides methods that respond to HTTP requests with HTTP errors.
    /// </summary>
    [Route("[controller]")]
    public sealed class ErrorController : Controller
    {
        #region Public Methods

        /// <summary>
        /// Gets the error view for the specified HTTP error status code. Returns a <see cref="PartialViewResult"/> if
        /// the request is an Ajax request, otherwise returns a full <see cref="ViewResult"/>.
        /// </summary>
        /// <param name="statusCode">The HTTP error status code.</param>
        /// <param name="status">The name of the HTTP error status code e.g. 'notfound'. This is not used but is here
        /// for aesthetic purposes.</param>
        /// <returns>A <see cref="PartialViewResult"/> if the request is an Ajax request, otherwise returns a full
        /// <see cref="ViewResult"/> containing the error view.</returns>
        [ResponseCache(CacheProfileName = CacheProfileName.Error)]
        [HttpGet("{statusCode:int:range(400, 599)}/{status?}", Name = ErrorControllerRoute.GetError)]
        public IActionResult Error(int statusCode, string status)
        {
            this.Response.StatusCode = statusCode;

            ActionResult result;
            if (this.Request.IsAjaxRequest())
            {
                // This allows us to show errors even in partial views.
                result = this.PartialView(ErrorControllerAction.Error, statusCode);
            }
            else
            {
                result = this.View(ErrorControllerAction.Error, statusCode);
            }

            return result;
        }

        #endregion
    }
}

HSMS/Controllers/SetupsController.cs
namespace com.bkss.Controllers
{
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;
    using Boilerplate.AspNetCore;
    using Boilerplate.AspNetCore.Filters;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using com.bkss.Constants;
    using com.bkss.Services;
    using com.bkss.Settings;
    using Microsoft.AspNetCore.Authorization;
    using System;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.AspNetCore.Identity;
    using IdentityModels;
    using ViewModels;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;
    using System.Collections.Generic;
    using System.Data;
    using System.Dynamic;
    using Microsoft.Net.Http.Headers;
    using System.IO;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OfficeOpenXml;
    using OfficeOpenXml.Style;
    using System.Drawing;

    [Authorize]
    public class SetupsController : Controller
    {
        #region Fields

        private readonly IServiceProvider serviceProvider;
        private readonly IOptions<AppSettings> appSettings;
        private readonly IBrowserConfigService browserConfigService;
#if NET461
        // The FeedService is not available for .NET Core because the System.ServiceModel.Syndication.SyndicationFeed
        // type does not yet exist. See https://github.com/dotnet/wcf/issues/76.
        private readonly IFeedService feedService;
#endif
        private readonly IManifestService manifestService;
        private readonly IOpenSearchService openSearchService;
        private readonly IRobotsService robotsService;
        private readonly ISitemapService sitemapService;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly AppCache appCache;
        #endregion

        #region Constructors

        public SetupsController(
            IBrowserConfigService browserConfigService,
#if NET461
            // The FeedService is not available for .NET Core because the System.ServiceModel.Syndication.SyndicationFeed
            // type does not yet exist. See https://github.com/dotnet/wcf/issues/76.
            IFeedService feedService,
#endif
            IManifestService manifestService,
            IOpenSearchService openSearchService,
            IRobotsService robotsService,
            ISitemapService sitemapService,
            IServiceProvider provider,
            IAppCacheService cache,
             IHostingEnvironment env,
            UserManager<ApplicationUser> userManager,
            IOptions<AppSettings> appSettings)
        {
            this.appSettings = appSettings;
            this.browserConfigService = browserConfigService;
#if NET461
            // The FeedService is not available for .NET Core because the System.ServiceModel.Syndication.SyndicationFeed
            // type does not yet exist. See https://github.com/dotnet/wcf/issues/76.
            this.feedService = feedService;
#endif
            this.manifestService = manifestService;
            this.openSearchService = openSearchService;
            this.robotsService = robotsService;
            this.sitemapService = sitemapService;
            this.serviceProvider = provider;
            this._userManager = userManager;
            this.hostingEnvironment = env;
            //
            this.appCache = (AppCache)cache;

            if(appCache.SchoolId == 0)
            {
                //Choose school
                RedirectToRoute(SetupsControllerRoute.GetIndex,new {m=2 });
            }
        }

        #endregion

        [HttpGet("setups", Name = SetupsControllerRoute.GetIndex)]
        public async Task<IActionResult> Index(int m, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            //var userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var scoped = serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope();
            var db = scoped.ServiceProvider.GetService<ApplicationDbContext>();

            ViewBag.Mode = m;
            //
            if (!db.Accounts.Any() || !db.Clients.Any())
            {
                return RedirectToRoute(HomeControllerRoute.GetIndex);
            }
            //
            if(Request.Query.Any(p=>p.Key == "msg"))
            {
                ViewBag.Message = Request.Query.Single(p => p.Key == "msg").Value;
            }else if(Request.Query.Any(p => p.Key == "err"))
            {
                ViewBag.Warning = Request.Query.Single(p => p.Key == "err").Value;
            }
            //
            if (Request.Query.Any(p => p.Key == "i"))
            {
                try
                {
                    ViewBag.Index = int.Parse(Request.Query.Single(p => p.Key == "i").Value);
                }
                catch { }
            }
            //
            //

            if (appCache.SchoolId == 0 && db.Schools.Include(p => p.CountrySchool).Any(o => o.CountrySchool.Name.Equals(appSettings.Value.Profile.Name)))
            {
                //
                var sch = db.Schools.Include(p => p.CountrySchool).SingleOrDefault(o => o.CountrySchool.Name.Equals(appSettings.Value.Profile.Name));
                if(sch != null)
                {
                    ViewBag.SchoolId = sch.Id;
                    ViewBag.School = sch.CountrySchool.Name;
                    //
                    appCache.SchoolId = sch.Id;
                }
            }
            //var q = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Schools'";
            //IEnumerable<string> columns = db.Set().FromSql(q);
            //using (var connection = db.Database.GetDbConnection())
            //{
            //    connection.Open();

            //    using (var command = connection.CreateCommand())
            //    {
            //        command.CommandText = q;
            //        var reader = command.ExecuteReader();
            //        var rowList = new List<object>();
            //        if (reader.HasRows)
            //        {
            //            while (reader.Read())
            //            {
            //                if (reader.FieldCount > 0)
            //                {
            //                    var values = new object[reader.FieldCount];
            //                    reader.GetValues(values);
            //                    // Add the array to the ArrayList
            //                    rowList.Add(values);
            //                }
            //                //reader.NextResult();
            //            }
            //        }
            //        else
            //        {
            //            Console.WriteLine("No rows found.");
            //        }
            //        //

            //        System.Diagnostics.Debug.WriteLine("Found  "+rowList.ToString());
            //        //var result = command.ExecuteScalar().ToString();
            //    }
            //}
            //ViewData["user"] = await userManager.FindByNameAsync(User.Identity.Name);
            return this.View(SetupsControllerAction.Index);
        }
        //Configure School
        [HttpPost("setups", Name = SetupsControllerRoute.GetIndex)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(AddSchoolViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            ViewBag.Index = 0;
            if(model.School > 0)
            {
                //var scoped = serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope();
                //var db = scoped.ServiceProvider.GetService<ApplicationDbContext>();
                //
                if (appCache.SchoolId == 0)
                    appCache.SchoolId = model.School;
                //
                return RedirectToRoute(SetupsControllerRoute.GetStart);
            }

            // If we got this far, something failed, redisplay form
            return View(SetupsControllerAction.Index);
        }
        //Choose School
        [HttpGet("chooseschool", Name = SetupsControllerRoute.ChooseSchool)]
        public async Task<IActionResult> ChooseSchool(int m, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            if (appCache.SchoolId > 0)
                return Redirect(returnUrl);
            //
            ViewBag.ReturenUrl = returnUrl;
            //
            return View(SetupsControllerAction.ChooseSchool);
        }
        [HttpPost("chooseschool", Name = SetupsControllerRoute.ChooseSchool)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChooseSchool(AddSchoolViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            ViewBag.Index = 0;
            if (model.School > 0)
            {
                //var scoped = serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope();
                //var db = scoped.ServiceProvider.GetService<ApplicationDbContext>();
                //
                if (appCache.SchoolId == 0)
                    appCache.SchoolId = model.School;
                //
                if(returnUrl != null)
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToRoute(SetupsControllerRoute.GetStart);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(SetupsControllerAction.ChooseSchool);
        }
        //
        // GET: /Setups/Schools/
        [HttpGet("start", Name = SetupsControllerRoute.GetStart)]

HSMS/Views/Setups/ChooseSchool.cshtml
@using Microsoft.EntityFrameworkCore;
@inject ApplicationDbContext dbContext
@inject IOptions<AppSettings> AppSettings
@model AddSchoolViewModel
@{
    //For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
    //
    var SchoolsList = new List<SelectListItem>();

    foreach (var s in dbContext.Schools.Include(j=>j.CountrySchool).ToList())
    {
        //
        SchoolsList.Add(new SelectListItem() { Value = "" + s.Id, Text = s.CountrySchool.Name, Selected = false });
    }

    Layout = "_SetupsLayout";
}
<style>
    .chosen-container-single .chosen-single{
        height:48px !important;
        line-height:48px;
        border-radius: 0px;
    }
</style>
<section>
    <form asp-controller="Setups" asp-action="Index" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
      <div>
          <div class="clear"></div>
          <div style="margin:auto;width:50%;min-width:300px;">
              <div style="margin:100px;box-shadow:#ccc 2px 2px;border-radius:2px 2px">
                  <!-- new widget -->
                  <div class="jarviswidget jarviswidget-color-blueDark">
                      <header>
                          <h2> Choose School </h2>
                      </header>

                      <!-- widget div-->
                      <div class="widget-body">
                          <!-- content goes here -->
                          <div>
                              <fieldset style="margin:10px">
                                  <div class="form-group">
                                      <label>Intergrated Schools</label>
                                      @Html.DropDownListFor(m=>m.School, SchoolsList, " -- Select School -- ", new { @class = "form-control chosen-select", style = "height:100% !important" })
                                  </div>
                              </fieldset>

                              <div class="form-actions">
                                  <div class="row">
                                      <div class="col-sm-1"  style="">
                                          <a class="btn btn-md btn-info" href="@Url.RouteUrl(SetupsControllerRoute.GetIndex,new {m=1 })" title="Integrate New School" style="cursor:pointer">
                                              <i class="fa fa-plus-circle"></i> New
                                          </a>
                                      </div>
                                      <div class="col-sm-11" style="">                                         
                                          <button class="btn btn-md btn-primary" type="submit" id="" title="Set as default School">
                                              Apply
                                          </button>
                                      </div>
                                  </div>
                              </div>
                          </div>

                          <!-- end content -->
                      </div>
                      <!-- end widget div -->
                  </div>
                  <!-- end widget -->
              </div>
          </div>
      </div>
    </form>
</section>

HSMS/Views/Setups/_AddDepartment.cshtml
@using Microsoft.EntityFrameworkCore;
@inject ApplicationDbContext dbContext
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@inject com.bkss.Services.IAppCacheService cache
@model AddDepartmentViewModel
@{
    var SchoolsList = new List<SelectListItem>();
    foreach (var s in dbContext.Schools.Include(l => l.CountrySchool).ToList())
    {
        SchoolsList.Add(new SelectListItem() { Value = "" + s.Id, Text = s.CountrySchool.Name, Selected = false });
    }
    var DeptTypes = new List<SelectListItem>();
    DeptTypes.Add(new SelectListItem() { Text = DepartmentType.Academic + "", Value = ((int)DepartmentType.Academic) + "" });
    DeptTypes.Add(new SelectListItem() { Text = DepartmentType.Welfare + "", Value = ((int)DepartmentType.Welfare) + "" });
    DeptTypes.Add(new SelectListItem() { Text = DepartmentType.Adminstration + "", Value = ((int)DepartmentType.Adminstration) + "" });
}

<section>
    <form asp-controller="Setups" asp-action="AddDepartment" asp-route-returnurl="@ViewData["ReturnUrl"]" method="POST" id="add-classroom-form">
        <div class="">
            <h3 style="">
                <br />
                <strong>Step 2 </strong> - Add Department
                <span class="font-sm" style="float:right">All Departments (@dbContext.Departments.Count())<span>
            </h3>
            <br />
            <div class="col-sm-12">

                <div class="row">

                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-home fa-lg fa-fw"></i></span>
                                <input class="form-control input-lg" placeholder="School" id="SchoolId" value="@cache.GetSchool().CountrySchool.Name" readonly="readonly">

                            </div>
                        </div>

                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-archive fa-lg fa-fw"></i></span>
                                <input class="form-control input-lg" placeholder="Department Name E.G Sciences,..." asp-for="DepartmentName">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-home fa-lg fa-fw"></i></span>
                                @Html.DropDownListFor(m => m.Type, DeptTypes, "-- Select Category --", new { @class = "form-control input-lg" })
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <div class="text-align-center">
            <hr />
            <button type="submit" class="btn btn-md btn-primary" id="save-class">
                <i class="fa fa-send"></i> &nbsp;<strong>Save Department</strong>
            </button>
        </div>
    </form>
</section>

HSMS/Views/Setups/_AddLevel.cshtml
@using Microsoft.EntityFrameworkCore;
@inject ApplicationDbContext dbContext
@inject IOptions<AppSettings> AppSettings

@inject com.bkss.Services.IAppCacheService cache
@model AddLevelViewModel
@{
    //For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
    //
}
<style>
    .chosen-container-single .chosen-single{
        height:48px !important;
        line-height:48px;
        border-radius: 0px;
    }
</style>
<section>
    <form asp-controller="Setups" asp-action="AddLevel" asp-route-returnurl="@ViewData["ReturnUrl"]" method="POST" id="add-year-form">
        <h3>
            <br />
            <strong>Step 2 </strong> - Add Academic Level
            <span class="font-sm" style="float:right">Levels (@dbContext.Levels.Count())<span>
        </h3>
        <br />
        <div class="col-sm-12">
            <div class="row">
                <div id="bootstrap-wizard-1" class="col-sm-12">
                    <section class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-home fa-lg fa-fw"></i></span>
                                        <input id="SchoolId" type="text" class="form-control input-lg" placeholder="Select School" value="@cache.GetSchool().CountrySchool.Name" readonly="readonly">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-user-md fa-lg fa-fw"></i></span>
                                        <input asp-for="Name" class="form-control input-lg" placeholder="Level Name, e.g From One" value="@Model.Name">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-user-md fa-lg fa-fw"></i></span>
                                        <input asp-for="Level" class="form-control input-lg" placeholder="Level Index, e.g 1,2,...4" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <div class="text-align-center">
            <hr />
            <button type="submit" class="btn btn-md btn-primary" id="save-school">
                <i class="fa fa-send"></i> &nbsp;<strong>Save Level</strong>
            </button>
        </div>
    </form>
</section>
@*<h3><strong>Step 1 </strong> - Academic Years</h3>

    <!-- wizard form starts here -->
    <fieldset>

        <div class="form-group has-warning">
            <label class="col-md-2 control-label">Input warning</label>
            <div class="col-md-10">
                <div class="input-group">
                    <input class="form-control" type="text">
                    <span class="input-group-addon"><i class="fa fa-warning"></i></span>
                </div>
                <span class="help-block">Something may have gone wrong</span>
            </div>

        </div>

        <div class="form-group has-error">
            <label class="col-md-2 control-label">Input error</label>
            <div class="col-md-10">
                <div class="input-group">
                    <input class="form-control" type="text">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-remove-circle"></i></span>
                </div>
                <span class="help-block"><i class="fa fa-warning"></i> Please correct the error</span>
            </div>
        </div>

        <div class="form-group has-success">
            <label class="col-md-2 control-label">Input success</label>
            <div class="col-md-10">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                    <input class="form-control" type="text">
                    <span class="input-group-addon"><i class="fa fa-check"></i></span>
                </div>
                <span class="help-block">Something may have gone wrong</span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Input icon success</label>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-sm-12">

                        <div class="input-icon-left">
                            <i class="fa txt-color-green fa-check"></i>
                            <input class="form-control" placeholder="Left Icon" type="text">
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </fieldset>*@

HSMS/Views/Setups/_AddOffice.cshtml
@using Microsoft.EntityFrameworkCore;
@inject ApplicationDbContext dbContext
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model AddOfficeViewModel
@{
    //
    var DepartmentsList = new List<SelectListItem>();
    int SchoolId = int.Parse("0" + ViewBag.SchoolId);
    if (SchoolId == 0 && dbContext.Schools.Count() > 0)
    {
        SchoolId = dbContext.Schools.First().Id;
    }
    School school = null;
    if(SchoolId > 0)
    {
        school = dbContext.Schools.Include(l => l.Streams).Single(p => p.Id == SchoolId);
        foreach (var s in dbContext.Departments.Include(l => l.School).Where(l => l.SchoolId == SchoolId && l.Type == DepartmentType.Adminstration).ToList())
        {
            DepartmentsList.Add(new SelectListItem() { Value = "" + s.Id, Text = s.Name, Selected = false });
        }

    }
}

<section>
    <form asp-controller="Setups" asp-action="AddOffice" asp-route-returnurl="@ViewData["ReturnUrl"]" method="POST" id="add-classroom-form">
        <div class="">
            <h3>
                <br />
                <strong>Step 5 </strong> - Add Offices
                <span class="font-sm" style="float:right">Total Offices(@(school!=null?dbContext.Offices.Include(k=>k.Department).Where(k=>k.Department.SchoolId==school.Id).Count()+"":"0"))</span>
            </h3>
            <br />
            <div class="col-sm-12">
                <div class="row">

                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope fa-lg fa-fw"></i></span>
                                <input class="form-control input-lg" placeholder="Office Name" type="text" asp-for="Name">

                            </div>
                        </div>

                    </div>

                </div>
                <div class="row">

                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope fa-lg fa-fw"></i></span>
                                <input class="form-control input-lg" placeholder="School Name" type="text" value="@school?.CountrySchool.Name" readonly>

                            </div>
                        </div>

                    </div>

                </div>
                <div class="row">

                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-map-marker fa-lg fa-fw"></i></span>
                                @Html.DropDownListFor(p => p.Department, DepartmentsList, "-- Select Department --", new { @class = "form-control input-lg" })

                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <div class="text-align-center">
            <hr />
            <button type="submit" class="btn btn-md btn-primary" id="save-class">
                <i class="fa fa-send"></i> &nbsp;<strong>Save Office</strong>
            </button>
        </div>
    </form>
</section>